### ISSUE TITLE
 there are 33 tests failed and two errors

### ISSUE THREAD

**Issue by Ryannn727** [horoc/cmu-15445#1]
![image](https://user-images.githubusercontent.com/49785444/218077782-5bbd0e2e-82b6-4885-8f06-ee6060eaf7ea.png)

I have successfully built the project and run ``` make check-tests```.
But there are 33 tests failed and two errors from the command.
Are the results as same as your results?

It will be my pleasure to your reply.

**Comment by horoc** [comment]
hi @Ryannn727 , thanks for your issue.

- First of all, this repository is used as personal records for studying cmu-15445.  It does not guarantee the correctness of the implementation and possibly has some bugs. Should be careful when referencing this in your implementation.
- And currently, I am working on the third project (B+Tree), and most of the fails you mentioned belong to project 4 or project 5.
- My test result of `check-tests` is 19 fails, maybe you should pull the latest version, like the BPlusTree Insert/Delete test should not be failed.

**Comment by Ryannn727** [comment]
Thanks for your replying and contribution! I thought u have finished all projects before, but never mind. Thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2023年2月10日(星期五) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [horoc/cmu-15445]  there are 33 tests failed and two errors (Issue #1)





 
hi @Ryannn727 , thanks for your issue.
  
First of all, this repository is used as personal records for studying cmu-15445.  It does not guarantee the correctness of the implementation and possibly has some bugs. Should be careful when referencing this to your implementation.
 
And currently, I am working on the second project, most of the fails you mentioned belong to project 3 or project 4.
 
My test result of check-tests is 19 fails, maybe you should pull the latest version, like the BPlusTree Insert/Delete test should not be failed.
